use_frameworks!

platform :ios, '8.0'

target 'NTAPI_Example' do
  pod 'NTAPI', :path => '../'

  target 'NTAPI_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
